package app.linkdesk;
import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.graphics.*;import android.hardware.display.*;import android.media.*;import android.media.projection.*;import android.os.*;import android.util.*;import android.view.*;import java.io.*;import org.json.*;
public class CaptureService extends Service {
 public static volatile boolean active=false,allowControl=false;public static volatile long heartbeat=0;private static volatile String latest=null;public static volatile int width=0,height=0;
 private MediaProjection projection;private VirtualDisplay display;private ImageReader reader;private HandlerThread thread;private Handler worker;private final Handler main=new Handler(Looper.getMainLooper());private PowerManager.WakeLock wake;private long last=0;
 public IBinder onBind(Intent i){return null;}
 public int onStartCommand(Intent intent,int flags,int id){if(intent==null||"stop".equals(intent.getAction())){stopSelf();return START_NOT_STICKY;}if(active)return START_NOT_STICKY;
 try{NotificationManager nm=getSystemService(NotificationManager.class);nm.createNotificationChannel(new NotificationChannel("session","Активное управление LinkDesk",NotificationManager.IMPORTANCE_LOW));PendingIntent stop=PendingIntent.getService(this,1,new Intent(this,CaptureService.class).setAction("stop"),PendingIntent.FLAG_IMMUTABLE);PendingIntent open=PendingIntent.getActivity(this,2,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE);Notification n=new Notification.Builder(this,"session").setContentTitle("LinkDesk: удалённое управление включено").setContentText("Ваш экран виден другому устройству. Нажмите ОСТАНОВИТЬ для отключения.").setSmallIcon(android.R.drawable.ic_menu_view).setOngoing(true).setContentIntent(open).addAction(new Notification.Action.Builder(null,"ОСТАНОВИТЬ",stop).build()).build();if(Build.VERSION.SDK_INT>=29)startForeground(1,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION);else startForeground(1,n);
 thread=new HandlerThread("LinkDeskCapture");thread.start();worker=new Handler(thread.getLooper());MediaProjectionManager manager=getSystemService(MediaProjectionManager.class);Intent grant=Build.VERSION.SDK_INT>=33?intent.getParcelableExtra("data",Intent.class):intent.getParcelableExtra("data");projection=manager.getMediaProjection(intent.getIntExtra("result",-1),grant);projection.registerCallback(new MediaProjection.Callback(){public void onStop(){active=false;main.post(()->stopSelf());}public void onCapturedContentResize(int w,int h){}},worker);
 DisplayMetrics metrics=new DisplayMetrics();getSystemService(WindowManager.class).getDefaultDisplay().getRealMetrics(metrics);width=metrics.widthPixels;height=metrics.heightPixels;int w=Math.min(width,1280),h=Math.round(height*(w/(float)width));reader=ImageReader.newInstance(w,h,PixelFormat.RGBA_8888,2);reader.setOnImageAvailableListener(r->{try(Image image=r.acquireLatestImage()){if(image==null||!active||System.currentTimeMillis()-last<90)return;last=System.currentTimeMillis();Image.Plane plane=image.getPlanes()[0];int stride=plane.getPixelStride(),padding=plane.getRowStride()-stride*w;Bitmap full=Bitmap.createBitmap(w+padding/stride,h,Bitmap.Config.ARGB_8888);full.copyPixelsFromBuffer(plane.getBuffer());Bitmap crop=Bitmap.createBitmap(full,0,0,w,h);ByteArrayOutputStream out=new ByteArrayOutputStream();crop.compress(Bitmap.CompressFormat.JPEG,55,out);latest="data:image/jpeg;base64,"+Base64.encodeToString(out.toByteArray(),Base64.NO_WRAP);if(crop!=full)crop.recycle();full.recycle();}catch(Exception e){active=false;main.post(()->stopSelf());}},worker);
 display=projection.createVirtualDisplay("LinkDesk",w,h,metrics.densityDpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,reader.getSurface(),null,worker);heartbeat=System.currentTimeMillis();active=true;wake=getSystemService(PowerManager.class).newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"linkdesk:session");wake.acquire(3600000);main.postDelayed(new Runnable(){public void run(){if(!active||System.currentTimeMillis()-heartbeat>20000){stopSelf();return;}main.postDelayed(this,2000);}},2000);
 }catch(Exception e){active=false;stopSelf();}return START_NOT_STICKY;}
 public static JSONObject frame()throws JSONException{return latest==null?null:new JSONObject().put("data",latest).put("width",width).put("height",height).put("editable",ControlService.instance!=null&&ControlService.instance.editable());}
 public void onDestroy(){active=false;allowControl=false;latest=null;main.removeCallbacksAndMessages(null);if(display!=null)display.release();if(reader!=null)reader.close();if(projection!=null)projection.stop();if(thread!=null)thread.quitSafely();if(wake!=null&&wake.isHeld())wake.release();MainActivity.stopped();super.onDestroy();}
}
