package app.linkdesk;
import android.accessibilityservice.*;import android.view.accessibility.*;import android.graphics.Path;import android.os.*;import android.media.AudioManager;import android.content.*;import org.json.*;
public class ControlService extends AccessibilityService {
 public static ControlService instance;protected void onServiceConnected(){instance=this;}public void onAccessibilityEvent(AccessibilityEvent e){focused=null;if(overlay!=null)overlay.focus(null);}public void onInterrupt(){clearOverlay();}public void onDestroy(){clearOverlay();instance=null;super.onDestroy();}
 private PointerOverlay overlay;private AccessibilityNodeInfo focused;private double scrollX=0,scrollY=0;private boolean scrollBusy=false;private final Handler handler=new Handler(Looper.getMainLooper());
 public void clearOverlay(){handler.removeCallbacksAndMessages(null);scrollBusy=false;scrollX=scrollY=0;pointerDown=false;focused=null;if(overlay!=null){try{getSystemService(android.view.WindowManager.class).removeView(overlay);}catch(Exception ignored){}overlay=null;}}
 private PointerOverlay overlay(){if(overlay==null){overlay=new PointerOverlay(this);android.view.WindowManager.LayoutParams p=new android.view.WindowManager.LayoutParams(-1,-1,android.view.WindowManager.LayoutParams.TYPE_ACCESSIBILITY_OVERLAY,android.view.WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|android.view.WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE|android.view.WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,android.graphics.PixelFormat.TRANSLUCENT);p.gravity=android.view.Gravity.TOP|android.view.Gravity.LEFT;if(Build.VERSION.SDK_INT>=28)p.layoutInDisplayCutoutMode=android.view.WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES;getSystemService(android.view.WindowManager.class).addView(overlay,p);}return overlay;}
 private void collect(AccessibilityNodeInfo n,java.util.List<AccessibilityNodeInfo> list,int[] budget){if(n==null||budget[0]--<=0)return;if(n.isVisibleToUser()&&n.isEnabled()&&(n.isClickable()||n.isEditable()||n.isFocusable()))list.add(n);for(int i=0;i<n.getChildCount()&&budget[0]>0;i++)collect(n.getChild(i),list,budget);}
 private void tab(boolean reverse){java.util.List<AccessibilityNodeInfo> nodes=new java.util.ArrayList<>();collect(getRootInActiveWindow(),nodes,new int[]{400});if(nodes.isEmpty())return;int index=nodes.indexOf(focused);index=index<0?(reverse?nodes.size()-1:0):Math.floorMod(index+(reverse?-1:1),nodes.size());focused=nodes.get(index);focused.performAction(AccessibilityNodeInfo.ACTION_FOCUS);android.graphics.Rect r=new android.graphics.Rect();focused.getBoundsInScreen(r);overlay().focus(r);}
 private void swipe(String key){float w=CaptureService.width,h=CaptureService.height;float x=w*.5f,y=h*.5f,tx=x,ty=y;switch(key){case "left":x=w*.78f;tx=w*.22f;break;case "right":x=w*.22f;tx=w*.78f;break;case "up":y=h*.75f;ty=h*.25f;break;case "down":y=h*.25f;ty=h*.75f;break;}gesture(x,y,tx,ty,160);overlay().pointer(tx,ty,false);}
 private void flushScroll(){if(scrollBusy||!CaptureService.active||!CaptureService.allowControl||System.currentTimeMillis()-CaptureService.heartbeat>20000){scrollX=scrollY=0;return;}double dx=scrollX,dy=scrollY;scrollX=scrollY=0;if(dx==0&&dy==0)return;float w=CaptureService.width,h=CaptureService.height;float tx=w*.5f,ty=h*.5f;if(Math.abs(dx)>Math.abs(dy))tx-=Math.signum(dx)*Math.min(w*.38,Math.max(w*.08,Math.abs(dx)));else ty-=Math.signum(dy)*Math.min(h*.38,Math.max(h*.08,Math.abs(dy)));Path path=new Path();path.moveTo(w*.5f,h*.5f);path.lineTo(tx,ty);scrollBusy=true;dispatchGesture(new GestureDescription.Builder().addStroke(new GestureDescription.StrokeDescription(path,0,110)).build(),new GestureResultCallback(){private void done(){scrollBusy=false;if(scrollX!=0||scrollY!=0)handler.post(ControlService.this::flushScroll);}public void onCompleted(GestureDescription g){done();}public void onCancelled(GestureDescription g){done();}},handler);}
 private void tap(float x,float y,long duration){java.util.List<AccessibilityNodeInfo> nodes=new java.util.ArrayList<>();collect(getRootInActiveWindow(),nodes,new int[]{400});float radius=18*getResources().getDisplayMetrics().density;double best=radius,second=Double.MAX_VALUE;android.graphics.Rect target=null;for(AccessibilityNodeInfo n:nodes){if(!n.isClickable()&&!n.isEditable())continue;android.graphics.Rect r=new android.graphics.Rect();n.getBoundsInScreen(r);if(r.isEmpty())continue;if(r.contains((int)x,(int)y)){gesture(x,y,x,y,duration);return;}double distance=Math.hypot(Math.max(r.left-x,Math.max(0,x-r.right)),Math.max(r.top-y,Math.max(0,y-r.bottom)));if(distance<best){second=best;best=distance;target=r;}else second=Math.min(second,distance);}if(target!=null&&second-best>4*getResources().getDisplayMetrics().density){x=Math.max(target.left+1,Math.min(target.right-1,x));y=Math.max(target.top+1,Math.min(target.bottom-1,y));}gesture(x,y,x,y,duration);overlay().pointer(x,y,false);}
 private float downX,downY;private long downTime;private boolean pointerDown=false;
 private float coord(JSONObject v,String key,int size)throws JSONException{double n=v.getDouble(key);if(!Double.isFinite(n)||n<0||n>1)throw new JSONException("coordinate");return(float)(n*(size-1));}
 private void gesture(float x,float y,float tx,float ty,long duration){Path p=new Path();p.moveTo(x,y);p.lineTo(tx,ty);dispatchGesture(new GestureDescription.Builder().addStroke(new GestureDescription.StrokeDescription(p,0,Math.max(50,Math.min(1500,duration)))).build(),null,null);}
 public boolean editable(){AccessibilityNodeInfo root=getRootInActiveWindow(),node=root==null?null:root.findFocus(AccessibilityNodeInfo.FOCUS_INPUT);return node!=null&&node.isEditable();}
 public void input(JSONObject v)throws JSONException{if(!CaptureService.allowControl||!CaptureService.active||System.currentTimeMillis()-CaptureService.heartbeat>20000)return;String type=v.optString("type");int w=CaptureService.width,h=CaptureService.height;
 if(type.equals("pointer")){String action=v.optString("action");overlay().pointer(coord(v,"x",w),coord(v,"y",h),action.equals("down")||(pointerDown&&!action.equals("up")));
  if(action.equals("click")||action.equals("long")){float x=coord(v,"x",w),y=coord(v,"y",h);tap(x,y,action.equals("long")?700:70);}
  else if(action.equals("down")||action.equals("drag")){downX=coord(v,"x",w);downY=coord(v,"y",h);downTime=System.currentTimeMillis();pointerDown=true;}
  else if(action.equals("move")){}
  else if(action.equals("up")){if(!pointerDown)return;pointerDown=false;float x=coord(v,"x",w),y=coord(v,"y",h);long dur=System.currentTimeMillis()-downTime;double dist=Math.hypot(x-downX,y-downY);if(dist<w*0.012f)tap(downX,downY,dur>600?700:70);else gesture(downX,downY,x,y,Math.max(60,Math.min(1500,dur)));}}
 else if(type.equals("gesture"))gesture(coord(v,"x",w),coord(v,"y",h),coord(v,"toX",w),coord(v,"toY",h),v.optLong("duration",300));
 else if(type.equals("scroll")){double dx=v.optDouble("x",0),dy=v.optDouble("y",0);if(!Double.isFinite(dx)||!Double.isFinite(dy))return;scrollX=Math.max(-2000,Math.min(2000,scrollX+dx));scrollY=Math.max(-2000,Math.min(2000,scrollY+dy));if(!scrollBusy){handler.removeCallbacks(scrollTask);handler.postDelayed(scrollTask,24);}}
 else if(type.equals("text")){String text=v.optString("text");if(text.length()>2000)return;AccessibilityNodeInfo root=getRootInActiveWindow(),focus=root==null?null:root.findFocus(AccessibilityNodeInfo.FOCUS_INPUT);if(focus!=null){Bundle args=new Bundle();String old=focus.getText()==null?"":focus.getText().toString();int start=focus.getTextSelectionStart(),end=focus.getTextSelectionEnd();if(start<0||end<0||start>old.length()||end>old.length()){start=old.length();end=start;}args.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,old.substring(0,Math.min(start,end))+text+old.substring(Math.max(start,end)));focus.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT,args);}}
 else if(type.equals("global"))global(v.optString("action"));
 else if(type.equals("tv")){String key=v.optString("key");AudioManager audio=getSystemService(AudioManager.class);switch(key){case "volume_up":audio.adjustStreamVolume(AudioManager.STREAM_MUSIC,AudioManager.ADJUST_RAISE,AudioManager.FLAG_SHOW_UI);break;case "volume_down":audio.adjustStreamVolume(AudioManager.STREAM_MUSIC,AudioManager.ADJUST_LOWER,AudioManager.FLAG_SHOW_UI);break;case "mute":audio.adjustStreamVolume(AudioManager.STREAM_MUSIC,AudioManager.ADJUST_TOGGLE_MUTE,AudioManager.FLAG_SHOW_UI);break;case "power":if(Build.VERSION.SDK_INT>=28)performGlobalAction(GLOBAL_ACTION_LOCK_SCREEN);break;case "up":if(Build.VERSION.SDK_INT>=33)performGlobalAction(GLOBAL_ACTION_DPAD_UP);break;case "down":if(Build.VERSION.SDK_INT>=33)performGlobalAction(GLOBAL_ACTION_DPAD_DOWN);break;case "left":if(Build.VERSION.SDK_INT>=33)performGlobalAction(GLOBAL_ACTION_DPAD_LEFT);break;case "right":if(Build.VERSION.SDK_INT>=33)performGlobalAction(GLOBAL_ACTION_DPAD_RIGHT);break;case "center":if(Build.VERSION.SDK_INT>=33)performGlobalAction(GLOBAL_ACTION_DPAD_CENTER);break;default:global(key);}}
 else if(type.equals("key")){String key=v.optString("key");if(java.util.Arrays.asList("left","right","up","down").contains(key))swipe(key);else if(key.equals("tab"))tab(v.optJSONArray("modifiers")!=null&&v.optJSONArray("modifiers").toString().contains("shift"));else if(key.equals("escape"))global("back");else if(key.equals("audio_vol_down"))input(new JSONObject().put("type","tv").put("key","volume_down"));else if(key.equals("audio_vol_up"))input(new JSONObject().put("type","tv").put("key","volume_up"));else if(key.equals("enter")&&focused!=null&&!focused.isEditable()&&focused.refresh()){focused.performAction(AccessibilityNodeInfo.ACTION_CLICK);}else if(key.equals("enter")){AccessibilityNodeInfo root=getRootInActiveWindow(),focus=root==null?null:root.findFocus(AccessibilityNodeInfo.FOCUS_INPUT);if(focus!=null&&Build.VERSION.SDK_INT>=30)focus.performAction(AccessibilityNodeInfo.AccessibilityAction.ACTION_IME_ENTER.getId());}else if(key.equals("backspace")){AccessibilityNodeInfo root=getRootInActiveWindow(),focus=root==null?null:root.findFocus(AccessibilityNodeInfo.FOCUS_INPUT);if(focus!=null&&focus.getText()!=null){String t=focus.getText().toString();int end=focus.getTextSelectionEnd();if(end>0&&end<=t.length()){Bundle args=new Bundle();args.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,t.substring(0,end-1)+t.substring(end));focus.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT,args);}}}}
 }
 private final Runnable scrollTask=this::flushScroll;
 private void global(String key){switch(key){case "home":performGlobalAction(GLOBAL_ACTION_HOME);break;case "back":performGlobalAction(GLOBAL_ACTION_BACK);break;case "recents":performGlobalAction(GLOBAL_ACTION_RECENTS);break;case "notifications":performGlobalAction(GLOBAL_ACTION_NOTIFICATIONS);break;}}
}
