package app.linkdesk;
import android.app.*;import android.os.*;import android.content.*;import android.content.res.Configuration;import android.media.projection.MediaProjectionManager;import android.provider.Settings;import android.webkit.*;import android.view.*;import androidx.webkit.WebViewAssetLoader;import org.json.*;import java.util.*;
public class MainActivity extends Activity {
 public static MainActivity current;private WebView web;private String approvalId;private final Handler handler=new Handler(Looper.getMainLooper());
 public void onCreate(Bundle b){super.onCreate(b);current=this;getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);web=new WebView(this);setContentView(web);WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);settings.setMediaPlaybackRequiresUserGesture(false);web.addJavascriptInterface(new Bridge(),"AndroidBridge");
 final WebViewAssetLoader loader=new WebViewAssetLoader.Builder().addPathHandler("/assets/",new WebViewAssetLoader.AssetsPathHandler(this)).build();
 web.setWebViewClient(new WebViewClient(){public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){return loader.shouldInterceptRequest(r.getUrl());}public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){String url=r.getUrl().toString();if(url.startsWith("https://appassets.androidplatform.net/assets/"))return false;if(url.startsWith("https://"))startActivity(new Intent(Intent.ACTION_VIEW,r.getUrl()));return true;}});web.setWebChromeClient(new WebChromeClient());web.loadUrl("https://appassets.androidplatform.net/assets/index.html");if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},100);
 }
 private void reply(String id,Object value,String error){handler.post(()->{if(web!=null)web.evaluateJavascript("window.linkdeskReply("+JSONObject.quote(id)+","+(value==null?"null":value instanceof String?JSONObject.quote((String)value):value.toString())+","+(error==null?"null":JSONObject.quote(error))+")",null);});}
 public static void stopped(){if(current!=null)current.handler.post(()->{if(current.web!=null)current.web.evaluateJavascript("window.linkdeskStopped && window.linkdeskStopped()",null);});}
 public static void rtcEvent(String room,String type,Object value){MainActivity a=current;if(a!=null)a.handler.post(()->{if(a.web!=null)a.web.evaluateJavascript("window.linkdeskRtcEvent?.("+JSONObject.quote(room)+","+JSONObject.quote(type)+","+(value instanceof String?JSONObject.quote((String)value):value.toString())+")",null);});}
 private void beginProjection(){MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);startActivityForResult(fullScreenCapture(m),42);}
 private void requestCapture(){if(Build.VERSION.SDK_INT>=29&&checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},43);else beginProjection();}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==43&&approvalId!=null)beginProjection();}
 private Intent fullScreenCapture(MediaProjectionManager m){return Build.VERSION.SDK_INT>=34?m.createScreenCaptureIntent(android.media.projection.MediaProjectionConfig.createConfigForDefaultDisplay()):m.createScreenCaptureIntent();}
 class Bridge { @JavascriptInterface public void call(String json){handler.post(()->{String id="";try{JSONObject b=new JSONObject(json);id=b.getString("id");String method=b.getString("method");JSONArray args=b.getJSONArray("args");switch(method){
 case "info": {boolean tv=(getResources().getConfiguration().uiMode&Configuration.UI_MODE_TYPE_MASK)==Configuration.UI_MODE_TYPE_TELEVISION;JSONObject o=new JSONObject().put("platform","android").put("nativeRTC",true).put("model",Build.MODEL).put("manufacturer",Build.MANUFACTURER).put("version",Build.VERSION.RELEASE).put("tv",tv).put("screens",new JSONArray().put(new JSONObject().put("id","default").put("name","Весь экран")));JSONArray tvKeys=new JSONArray(Arrays.asList("volume_down","volume_up","mute","home","back","recents","power"));if(Build.VERSION.SDK_INT>=33)for(String k:Arrays.asList("up","down","left","right","center"))tvKeys.put(k);o.put("tvKeys",tvKeys);reply(id,o,null);break;}
 case "copy": {String value=args.getString(0);if(value.length()>2048)throw new Exception("Слишком длинный текст");getSystemService(android.content.ClipboardManager.class).setPrimaryClip(ClipData.newPlainText("LinkDesk",value));reply(id,true,null);break;}
 case "permissions": startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));reply(id,"Включите службу LinkDesk. Она действует только после подтверждения сеанса. Для управления всем экраном в системном запросе выберите «Весь экран».",null);break;
 case "approve": {if(CaptureService.active){reply(id,false,null);break;}final String requestId=id;new AlertDialog.Builder(MainActivity.this).setTitle("Разрешить управление?").setMessage(args.optString(0)+" просит просмотр экрана, системный звук, нажатия и ввод текста. Разрешение на аудио нужно только для звука приложений, микрофон не записывается. Код проверки: "+args.optString(1)+". Остановить можно через уведомление LinkDesk.").setNegativeButton("Отклонить",(d,w)->reply(requestId,false,null)).setOnCancelListener(d->reply(requestId,false,null)).setNeutralButton("Только наблюдение",(d,w)->{CaptureService.allowControl=false;approvalId=requestId;requestCapture();}).setPositiveButton("Управление",(d,w)->{if(ControlService.instance==null){startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));reply(requestId,null,"Включите службу LinkDesk в разделе «Специальные возможности», затем снова подтвердите подключение на этом устройстве.");return;}CaptureService.allowControl=true;approvalId=requestId;requestCapture();}).show();break;}
 case "rtcStart":if(!CaptureService.active||CaptureService.rtc==null)throw new Exception("Нет активного разрешения");CaptureService.rtc.start(args.getString(0));reply(id,true,null);break;
 case "rtcSignal":if(!CaptureService.active||CaptureService.rtc==null)throw new Exception("Нет активного разрешения");CaptureService.rtc.signal(args.getJSONObject(0));reply(id,true,null);break;
 case "rtcSend":if(!CaptureService.active||CaptureService.rtc==null)throw new Exception("Нет активного разрешения");reply(id,CaptureService.rtc.send(args.getString(0)),null);break;
 case "editable":reply(id,ControlService.instance!=null&&ControlService.instance.editable(),null);break;
 case "heartbeat":if(!CaptureService.active)throw new Exception("Сеанс остановлен");CaptureService.heartbeat=System.currentTimeMillis();reply(id,true,null);break;
 case "capture": if(!CaptureService.active)throw new Exception("Нет доступа к экрану");reply(id,CaptureService.frame(),null);break;
 case "input":if(!CaptureService.active||System.currentTimeMillis()-CaptureService.heartbeat>20000)throw new Exception("Нет активного разрешения");if(ControlService.instance!=null)ControlService.instance.input(args.getJSONObject(0));reply(id,true,null);break;
 case "stop":CaptureService.active=false;stopService(new Intent(MainActivity.this,CaptureService.class));reply(id,true,null);break;
 default:reply(id,null,"Unknown method");
 }}catch(Exception e){reply(id,null,e.getMessage());}});}}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==42){String id=approvalId;approvalId=null;if(result!=RESULT_OK||data==null){reply(id,false,null);return;}Intent service=new Intent(this,CaptureService.class).putExtra("result",result).putExtra("data",data);startForegroundService(service);handler.postDelayed(new Runnable(){int attempts=0;public void run(){if(CaptureService.active){try{reply(id,new JSONObject().put("control",CaptureService.allowControl),null);}catch(Exception e){reply(id,null,e.getMessage());}}else if(++attempts<30)handler.postDelayed(this,200);else reply(id,null,"Не удалось включить захват экрана");}},200);}}
 @Override public void onBackPressed(){if(CaptureService.active)new AlertDialog.Builder(this).setTitle("Завершить доступ?").setPositiveButton("Остановить",(d,w)->{CaptureService.active=false;stopService(new Intent(this,CaptureService.class));stopped();}).setNegativeButton("Продолжить",null).show();else super.onBackPressed();}
 protected void onDestroy(){CaptureService.active=false;stopService(new Intent(this,CaptureService.class));current=null;if(web!=null){web.removeJavascriptInterface("AndroidBridge");web.destroy();web=null;}super.onDestroy();}
}
