import fs from 'node:fs/promises';import path from 'node:path';import {build} from 'esbuild';import sharp from 'sharp';
await fs.mkdir('web/vendor',{recursive:true});await build({stdin:{contents:"import QRCode from 'qrcode'; window.QRCode=QRCode;",resolveDir:process.cwd()},bundle:true,minify:true,outfile:'web/vendor/qrcode.js'});
for(const size of [192,512])await sharp('web/icon.svg').resize(size,size).png().toFile(`web/icon-${size}.png`);
await fs.mkdir('android/app/src/main/res/drawable',{recursive:true});await sharp('web/icon.svg').resize(192,192).png().toFile('android/app/src/main/res/drawable/icon.png');
await sharp({create:{width:320,height:180,channels:4,background:'#183d2e'}}).composite([{input:await sharp('web/icon.svg').resize(150,150).png().toBuffer(),gravity:'center'}]).png().toFile('android/app/src/main/res/drawable/banner.png');
await fs.mkdir('android/app/src/main/assets',{recursive:true});await fs.cp('web','android/app/src/main/assets',{recursive:true});
for(const dir of ['dist/site','dist/ios']){await fs.mkdir(dir,{recursive:true});await fs.cp('web',dir,{recursive:true});await fs.writeFile(path.join(dir,'vercel.json'),JSON.stringify({cleanUrls:true,headers:[{source:'/(.*)',headers:[{key:'X-Content-Type-Options',value:'nosniff'},{key:'Referrer-Policy',value:'no-referrer'},{key:'X-Frame-Options',value:'DENY'},{key:'Permissions-Policy',value:'camera=(), microphone=(), geolocation=()'},{key:'Content-Security-Policy',value:"default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://tekynylmdmopjbhkboci.supabase.co; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"}]}]}));}
let installer=await fs.readFile('web/index.html','utf8');
installer=installer.replace(/<section id="connect"[\s\S]*?<section id="ios-note"/, '<section id="ios-note"');
installer=installer.replace(/<dialog id="session"[\s\S]*<script src="\.\/config.js">/, '<script src="./config.js">');
installer=installer.replace('<script src="./vendor/qrcode.js"></script>','').replace('src="./app.mjs"','src="./installer.mjs"');
installer=installer.replace('href="#connect">Подключиться','href="#downloads">Скачать').replace('Установите LinkDesk, чтобы передавать экран и разрешать управление.','');
await fs.writeFile('dist/site/index.html',installer);
for(const name of ['app.mjs','immersive.mjs','crypto.mjs','sw.js','client.html'])await fs.rm('dist/site/'+name,{force:true});
let client=await fs.readFile('web/index.html','utf8');
client=client.replace('<body>','<body class="app-shell">').replace(/<header>[\s\S]*?<\/header>/,'<header class="app-header"><span class="brand"><span class="mark">↗</span>LinkDesk</span><span class="app-badge">ЗАЩИЩЁННЫЙ ДОСТУП</span><span class="app-version">0.1 Preview</span></header>');
client=client.replace(/<section class="intro">[\s\S]*?<section id="connect"/,'<div class="app-welcome"><p>РАБОЧЕЕ ПРОСТРАНСТВО</p><h1>Какое устройство подключим?</h1><span>Всё начинается с вашего разрешения.</span></div><section id="connect"');
client=client.replace(/<section id="downloads">[\s\S]*?<\/main>/,'</main>').replace(/<footer>[\s\S]*?<\/footer>/,'');
client=client.replace('<title>LinkDesk — ваши устройства рядом</title>','<title>LinkDesk — устройства</title>').replace('<link rel="stylesheet" href="./style.css">','<link rel="stylesheet" href="./style.css"><link rel="stylesheet" href="./client.css">');
client=client.replace(/<div id="host-browser">[\s\S]*?<div id="host-native"/,'<div id="host-browser"><p>Приём доступа доступен в установленном клиенте Windows, Mac или Android.</p></div><div id="host-native"');
await fs.writeFile('web/client.html',client);await fs.writeFile('android/app/src/main/assets/index.html',client);await fs.writeFile('dist/ios/index.html',client.replace('</body>','<script type="module" src="./install.mjs"></script></body>'));
await fs.copyFile('web/client.css','android/app/src/main/assets/client.css');await fs.copyFile('web/client.css','dist/ios/client.css');
const routes={windows:'LinkDesk-Windows-0.1.0.exe',mac:'LinkDesk-Mac-arm64-0.1.0.zip','mac-intel':'LinkDesk-Mac-x64-0.1.0.zip',android:'LinkDesk-Android-0.1.0.apk'};
const settings=JSON.parse(await fs.readFile('dist/site/vercel.json','utf8'));settings.redirects=Object.entries(routes).map(([key,file])=>({source:'/download/'+key,destination:'https://github.com/isabekdanial33-gif/linkdesk/releases/download/v0.1.0/'+file,permanent:false}));await fs.writeFile('dist/site/vercel.json',JSON.stringify(settings));
console.log('Installer-only website, iOS PWA and native assets built.');
