import {random,sha,keys,seal,unseal} from './crypto.mjs';
const $=s=>document.querySelector(s),config=window.LINKDESK_CONFIG;
let native=window.linkdesk,info=null,state=null,busy=false,touchMode=false,drag=false,modifier=false,pointer={x:.5,y:.5},touchStart=null,lastMove=0;
const nativePending=new Map();
window.linkdeskReply=(id,value,error)=>{const p=nativePending.get(id);if(!p)return;nativePending.delete(id);clearTimeout(p.timer);error?p.reject(Error(error)):p.resolve(value);};
if(window.AndroidBridge)native=new Proxy({},{get:(_,method)=>(...args)=>new Promise((resolve,reject)=>{const id=random(8),timer=setTimeout(()=>{nativePending.delete(id);reject(Error('Приложение не ответило. Повторите действие.'));},120000);nativePending.set(id,{resolve,reject,timer});window.AndroidBridge.call(JSON.stringify({id,method,args}));})});
window.linkdeskStopped=()=>stop('Доступ остановлен на этом устройстве');
window.addEventListener('linkdesk-native-stopped',window.linkdeskStopped);
function notice(text,error=false){const n=$('#status');n.textContent=text;n.hidden=false;n.classList.toggle('error',error);clearTimeout(notice.timer);notice.timer=setTimeout(()=>n.hidden=true,9000);}
function fail(e){notice(e.message||String(e),true);}
function bind(selector,event,fn){$(selector)?.addEventListener(event,e=>Promise.resolve(fn(e)).catch(fail));}
function uiStatus(t){$('#transport').textContent=t;}
async function api(action,extra={},s=state){const response=await fetch(config.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:s.id,role:s.role,token:s.token,...extra}),signal:AbortSignal.timeout(15000)});const b=await response.json();if(!response.ok){const e=Error(b.error||'Сервер недоступен');e.status=response.status;throw e;}return b;}
function fresh(role,id,password,k,token){return {role,id,password,key:k.key,auth:k.auth,token,queue:[],since:0,seq:0,received:0,frameSeq:0,lastFrame:0,approved:false,closed:false,lastOk:Date.now(),lastPeer:Date.now(),frameAt:null,pc:null,dc:null,chunks:null};}
async function envelope(s,value){return seal(s.key,{...value,seq:++s.seq},s.id+'/'+s.role);}
async function queue(value,s=state){if(!s||s.closed)return;s.queue.push(await envelope(s,value));}
async function send(value){const s=state;if(!s||s.closed)return;if(s.role==='guest'&&!s.approved)return;const packet=await envelope(s,value);if(s.dc?.readyState==='open'&&s.dc.bufferedAmount<256000)s.dc.send(packet);else if(s.queue.length<100)s.queue.push(packet);}
async function startHost(){if(state||busy)return;busy=true;$('#host-button').disabled=true;try{const id=random(),password=random(12),k=await keys(id,password),token=random(32);const s=fresh('host',id,password,k,token);await api('create',{hostToken:token,joinHash:await sha(k.auth)},s);state=s;$('#host-native').hidden=true;$('#host-details').hidden=false;$('#host-id').textContent=id;$('#host-password').textContent=password;$('#host-description').textContent='Ожидаем подключения. Экран и управление пока не передаются.';if(window.QRCode)await QRCode.toCanvas($('#qr'),config.ios+'/#room='+id,{width:160,margin:1,color:{dark:'#183d2e',light:'#edf2e5'}});poll(s);notice('Код готов. Передайте пароль отдельно.');}finally{busy=false;$('#host-button').disabled=false;}}
async function connect(e){e.preventDefault();if(state||busy)return;busy=true;$('#connect-button').disabled=true;try{const id=$('#room-input').value.replace(/[\s-]/g,'').toLowerCase(),password=$('#password-input').value.trim();if(!/^[a-f0-9]{32}$/.test(id))throw Error('Введите полный код из 32 символов с другого устройства.');if(password.length<12)throw Error('Введите пароль сеанса полностью.');const k=await keys(id,password),token=random(32),s=fresh('guest',id,password,k,token);await api('join',{auth:k.auth,guestToken:token},s);state=s;$('#password-input').value='';$('#session').showModal();$('#session-title').textContent='Ожидаем разрешения';$('#screen-placeholder').hidden=false;$('#screen-placeholder').textContent='Подтвердите подключение на другом устройстве.';await queue({type:'hello',name:info?.model||(/iPhone|iPad/.test(navigator.userAgent)?'iPhone / iPad':navigator.userAgent.includes('Android')?'Android':'Веб-пульт')},s);poll(s);try{await navigator.wakeLock?.request('screen');}catch{} }finally{busy=false;$('#connect-button').disabled=false;}}
async function stop(reason='Сеанс завершён'){const s=state;if(!s)return;s.closed=true;state=null;native?.stop().catch(()=>{});s.pc?.close();s.stream?.getTracks().forEach(t=>t.stop());$('#remote-video').srcObject=null;$('#remote-video').hidden=true;$('#remote-screen').hidden=false;$('#viewport').hidden=false;$('#session').classList.remove('tv-session');clearTimeout(s.frameTimer);clearTimeout(s.timer);api('close',{},s).catch(()=>{});$('#session').close();$('#remote-screen').removeAttribute('src');$('#host-details').hidden=true;$('#host-native').hidden=!native;$('#host-password').textContent='';$('#host-id').textContent='';$('#host-description').textContent=native?'Создайте новый код для следующего подключения.':'Установите LinkDesk для передачи экрана.';$('#tv-remote')?.remove();drag=false;modifier=false;notice(reason);}
async function poll(s){if(s.closed)return;let out=[];try{out=s.queue.splice(0,12);const frame=s.pendingFrame;s.pendingFrame=null;const r=await api('sync',{messages:out,since:s.since,frameAt:s.frameAt,...(frame?{frame}:{})},s);if(s.closed)return;s.lastOk=Date.now();if(s.role==='host'&&s.approved)await native.heartbeat();if(r.frame){await receiveFrame(r.frame,s);s.frameAt=r.frameAt;}for(const m of r.messages){s.since=Math.max(s.since,m.id);await receive(m.payload,s);}if(s.approved&&Date.now()-s.lastPeer>20000){await stop('Связь с устройством потеряна. Создайте новый сеанс.');return;}}catch(e){if(s.closed)return;s.queue.unshift(...out);if([401,403,404].includes(e.status)||Date.now()-s.lastOk>20000){await stop(e.message);return;}uiStatus('Связь прервалась. Восстанавливаем…');}s.timer=setTimeout(()=>poll(s),s.dc?.readyState==='open'?1800:650);}
async function receive(packet,s){if(s.closed)return;const value=await unseal(s.key,packet,s.id+'/'+(s.role==='host'?'guest':'host'));if(!Number.isSafeInteger(value.seq)||value.seq<=s.received)return;s.received=value.seq;s.lastPeer=Date.now();
 if(value.type==='hello'&&s.role==='host'&&!s.prompted){s.prompted=true;const sas=(await sha(s.auth)).slice(0,6).toUpperCase();const approved=await native.approve(String(value.name).slice(0,80),sas,$('#screen-select').value);if(s.closed){await native.stop();return;}if(!approved){await stop('Запрос отклонён');return;}s.approved=true;s.lastPeer=Date.now();s.control=approved.control!==false;await api('approve',{},s);await queue({type:'approved',info:{...info,control:s.control},sas},s);if(info.platform!=='android'){try{s.stream=await navigator.mediaDevices.getDisplayMedia({audio:false,video:{frameRate:30,width:1920,height:1080}});s.stream.getVideoTracks()[0].onended=()=>stop('Передача экрана остановлена');}catch{}}$('#host-description').textContent='Сейчас вашим устройством управляют. Нажмите «Закрыть доступ» для остановки.';startPeer(s,true);frames(s);}
 else if(value.type==='approved'&&s.role==='guest'){s.approved=true;s.remoteInfo=value.info;$('#session-title').textContent=value.info.model||value.info.platform;uiStatus('Защищённый резервный канал · '+value.sas);$('#screen-placeholder').textContent='Получаем экран…';document.querySelectorAll('[data-global]').forEach(b=>b.hidden=value.info.platform!=='android');if(value.info.tv)makeTvRemote(value.info);window.dispatchEvent(new CustomEvent('linkdesk-connected',{detail:value.info}));}
 else if(value.type==='signal'){await handleSignal(value,s);}
 else if(value.type==='input'&&s.role==='host'&&s.approved&&s.control){await native.input(value.event);}
 else if(value.type==='quality'&&s.role==='host'&&['fast','balanced','sharp'].includes(value.value)){s.quality=value.value;}
 else if(value.type==='ping'){if(value.editable!==undefined)window.dispatchEvent(new CustomEvent('linkdesk-editable',{detail:value.editable}));if(s.role==='host'&&s.approved)await native.heartbeat();}
}
function startPeer(s,offer=false){if(s.pc)return s.pc;const pc=s.pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});if(s.stream)for(const track of s.stream.getTracks())pc.addTrack(track,s.stream);pc.ontrack=e=>{const video=$('#remote-video');video.srcObject=e.streams[0];video.hidden=false;$('#remote-screen').hidden=true;$('#screen-placeholder').hidden=true;video.play().catch(()=>{});};pc.onicecandidate=e=>{if(e.candidate)queue({type:'signal',candidate:e.candidate.toJSON()},s).catch(()=>{});};pc.ondatachannel=e=>attachChannel(e.channel,s);pc.onconnectionstatechange=()=>{if(pc.connectionState==='connected'){uiStatus('Прямое зашифрованное соединение');}else if(['failed','disconnected','closed'].includes(pc.connectionState))uiStatus('Защищённый резервный канал · ~1 кадр/с');};if(offer){attachChannel(pc.createDataChannel('linkdesk',{ordered:true}),s);(async()=>{await pc.setLocalDescription(await pc.createOffer());await queue({type:'signal',description:pc.localDescription.toJSON()},s);})().catch(()=>{});}return pc;}
async function handleSignal(v,s){if(!s.approved)return;const pc=startPeer(s);if(v.description){await pc.setRemoteDescription(v.description);for(const c of s.candidates||[])await pc.addIceCandidate(c);s.candidates=[];if(v.description.type==='offer'){await pc.setLocalDescription(await pc.createAnswer());await queue({type:'signal',description:pc.localDescription.toJSON()},s);}}else if(v.candidate){if(pc.remoteDescription)await pc.addIceCandidate(v.candidate);else(s.candidates??=[]).push(v.candidate);}}
function attachChannel(dc,s){s.dc=dc;dc.onmessage=e=>{const t=e.data;if(typeof t!=='string'||t.length>600000)return;if(t.startsWith('F:')){const parts=t.split(':');const n=Number(parts[1]);if(!Number.isInteger(n)||n<1||n>50)return;s.chunks={n,parts:[],time:Date.now()};}else if(t.startsWith('C:')){const c=s.chunks;if(!c||Date.now()-c.time>5000)return;c.parts.push(t.slice(2));if(c.parts.length===c.n){s.chunks=null;receiveFrame(c.parts.join(''),s).catch(()=>{});}}else receive(t,s).catch(()=>{});};dc.onclose=()=>uiStatus('Защищённый резервный канал · ~1 кадр/с');}
async function frames(s){if(s.closed||!s.approved)return;const fast=s.dc?.readyState==='open';try{if(fast&&s.stream){await send({type:'ping',editable:await native.editable()});s.frameTimer=setTimeout(()=>frames(s),600);return;}const frame=await native.capture(s.quality||'balanced');if(s.closed)return;if(frame){const payload=await seal(s.key,{...frame,seq:++s.frameSeq},s.id+'/frame');if(fast&&s.dc.bufferedAmount<256000){const n=Math.ceil(payload.length/14000);s.dc.send('F:'+n);for(let i=0;i<n;i++)s.dc.send('C:'+payload.slice(i*14000,(i+1)*14000));}else if(!fast)s.pendingFrame=payload;}}catch(e){await stop('Передача экрана остановлена: '+e.message);return;}s.frameTimer=setTimeout(()=>frames(s),fast?100:1000);}
async function receiveFrame(packet,s){if(s.role!=='guest'||s.closed)return;const v=await unseal(s.key,packet,s.id+'/frame');if(v.seq<=s.lastFrame||!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(v.data)||v.data.length>500000)return;s.lastFrame=v.seq;s.lastPeer=Date.now();$('#remote-screen').src=v.data;window.dispatchEvent(new CustomEvent('linkdesk-editable',{detail:!!v.editable}));$('#screen-placeholder').hidden=true;}
export function input(event){if(state?.remoteInfo?.control===false)return;send({type:'input',event}).catch(fail);}
function point(e){const img=$('#remote-screen'),r=img.getBoundingClientRect();if(!img.naturalWidth||!r.width)return null;return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
const viewport=$('#viewport');
export const getSession=()=>state;

/* Legacy pointer implementation replaced by immersive.mjs
viewport.addEventListener('pointerdown',e=>{if(!state?.approved)return;const p=point(e);if(!p)return;e.preventDefault();viewport.focus();viewport.setPointerCapture(e.pointerId);pointer=p;touchStart={...p,cx:e.clientX,cy:e.clientY,time:Date.now(),pointerType:e.pointerType};if(e.pointerType==='mouse')input({type:'pointer',...p,action:'down',button:e.button===2?'right':'left'});});
viewport.addEventListener('pointermove',e=>{if(!state?.approved)return;const p=point(e);if(!p)return;const now=Date.now();if(now-lastMove<40)return;lastMove=now;if(e.pointerType==='mouse'){pointer=p;input({type:'pointer',...p,action:'move'});}else if(touchStart&&touchMode){const r=viewport.getBoundingClientRect();pointer.x=Math.max(0,Math.min(1,pointer.x+(e.clientX-touchStart.cx)/r.width));pointer.y=Math.max(0,Math.min(1,pointer.y+(e.clientY-touchStart.cy)/r.height));touchStart.cx=e.clientX;touchStart.cy=e.clientY;input({type:'pointer',...pointer,action:drag?'drag':'move'});const cur=$('#touch-cursor');cur.hidden=false;cur.style.left=pointer.x*100+'%';cur.style.top=pointer.y*100+'%';}});
viewport.addEventListener('pointerup',e=>{if(!touchStart)return;const p=point(e)||pointer,start=touchStart;touchStart=null;if(e.pointerType==='mouse')input({type:'pointer',...p,action:'up',button:e.button===2?'right':'left'});else if(touchMode){if(Date.now()-start.time<250)input({type:'pointer',...pointer,action:'click',button:'left'});else if(drag)input({type:'pointer',...pointer,action:'up',button:'left'});}else{pointer=p;const distance=Math.hypot(p.x-start.x,p.y-start.y);input(distance<.015?{type:'pointer',...p,action:Date.now()-start.time>600?'long':'click',button:'left'}:{type:'gesture',x:start.x,y:start.y,toX:p.x,toY:p.y,duration:Math.min(1500,Date.now()-start.time)});}});
viewport.addEventListener('pointercancel',()=>{touchStart=null;input({type:'pointer',...pointer,action:'up',button:'left'});});
viewport.addEventListener('contextmenu',e=>e.preventDefault());viewport.addEventListener('wheel',e=>{e.preventDefault();input({type:'scroll',x:e.deltaX,y:e.deltaY});},{passive:false});
*/
const keyMap={Enter:'enter',Escape:'escape',Backspace:'backspace',Tab:'tab',Delete:'delete',ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',Home:'home',End:'end',PageUp:'pageup',PageDown:'pagedown',' ':'space',Meta:'command',Control:'control',Alt:'alt',Shift:'shift'};
viewport.addEventListener('keydown',e=>{if(['Shift','Control','Alt','Meta'].includes(e.key))return;if(e.key==='Escape'){viewport.blur();return;}e.preventDefault();const key=keyMap[e.key]||e.key.toLowerCase();if(e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey)input({type:'text',text:e.key});else input({type:'key',key,modifiers:[e.ctrlKey?'control':null,e.metaKey?'command':null,e.altKey?'alt':null,e.shiftKey?'shift':null].filter(Boolean)});});
document.querySelectorAll('[data-key]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.key;if(key==='command'){modifier=!modifier;b.setAttribute('aria-pressed',modifier);return;}input({type:'key',key:key==='alt-tab'?'tab':key,modifiers:key==='alt-tab'?['alt']:modifier?[state?.remoteInfo?.platform==='darwin'?'command':'control']:[]});modifier=false;$('#modifier').setAttribute('aria-pressed','false');}));
document.querySelectorAll('[data-global]').forEach(b=>b.addEventListener('click',()=>input({type:'global',action:b.dataset.global})));
function makeTvRemote(device){$('#tv-remote')?.remove();const wrap=document.createElement('section');wrap.id='tv-remote';wrap.className='tv-remote';const title=document.createElement('h3');title.textContent=(device.manufacturer||'Android TV')+' · '+device.model;wrap.append(title);const sub=document.createElement('p');sub.textContent='Android '+device.version+' · Пульт для этой системы';wrap.append(sub);const buttons=[['⏻','power'],['Источник','source'],['⌂','home'],['↑','up'],['←','left'],['OK','center'],['→','right'],['↓','down'],['Назад','back'],['VOL −','volume_down'],['Без звука','mute'],['VOL +','volume_up'],['CH −','channel_down'],['Приложения','recents'],['CH +','channel_up'],['⏮','previous'],['⏯','play_pause'],['⏭','next'],...Array.from({length:10},(_,n)=>[String(n),String(n)])];for(const [label,key]of buttons){const b=document.createElement('button');b.textContent=label;b.className='secondary';b.disabled=!(device.tvKeys||[]).includes(key);b.title=b.disabled?'Система не предоставляет эту команду':label;b.addEventListener('click',()=>input({type:'tv',key}));wrap.append(b);}$('#session-workspace').append(wrap);$('#session').classList.add('tv-session');viewport.hidden=false;}
bind('#connect-form','submit',connect);bind('#host-button','click',startHost);bind('#stop-host','click',()=>stop());bind('#disconnect','click',()=>stop());bind('#session','cancel',e=>{e.preventDefault();stop();});bind('#show-password','click',()=>{$('#password-input').type=$('#password-input').type==='password'?'text':'password';});
bind('#copy-id','click',async()=>{await navigator.clipboard.writeText(state.id);notice('Код скопирован');});bind('#copy-password','click',async()=>{await navigator.clipboard.writeText(state.password);notice('Пароль скопирован');});bind('#permissions','click',async()=>notice(await native.permissions()));
bind('#touch-mode','click',()=>{touchMode=!touchMode;$('#touch-mode').textContent=touchMode?'Касание: трекпад':'Касание: прямо';$('#touch-cursor').hidden=!touchMode;});bind('#right-click','click',()=>input({type:'pointer',...pointer,action:'click',button:'right'}));bind('#drag-toggle','click',()=>{drag=!drag;$('#drag-toggle').setAttribute('aria-pressed',drag);if(!drag)input({type:'pointer',...pointer,action:'up',button:'left'});});
bind('#quality','change',()=>send({type:'quality',value:$('#quality').value}));bind('#text-form','submit',e=>{e.preventDefault();if(!state?.approved)return;input({type:'text',text:$('#remote-text').value});$('#remote-text').value='';});bind('#fullscreen','click',async()=>{if(document.fullscreenElement)await document.exitFullscreen();else if($('#session').requestFullscreen)await $('#session').requestFullscreen();else notice('На iPhone откройте PWA с главного экрана для максимальной площади.');});
window.addEventListener('pagehide',()=>{native?.stop().catch(()=>{});if(state){state.pc?.close();state.closed=true;}});
setInterval(()=>{if(state?.approved)send({type:'ping'}).catch(()=>{});},3000);
const isIos=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)||location.hostname.includes('linkdesk-ios');if(isIos){document.body.classList.add('ios-mode');$('#ios-note').hidden=false;document.title='LinkDesk — пульт для iPhone';}
const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('room')){$('#room-input').value=hash.get('room');history.replaceState(null,'',location.pathname);}
$('#ios-link').href=config.ios;document.querySelectorAll('[data-asset]').forEach(a=>a.href=config.downloads.replace('/tag/','/download/')+'/'+a.dataset.asset);
if(native){try{info=await native.info();$('#host-native').hidden=false;$('#host-browser').hidden=true;$('#host-description').textContent='Доступ включится только после отдельного подтверждения запроса.';for(const display of info.screens||[{id:'default',name:'Весь экран'}]){const o=document.createElement('option');o.value=display.id;o.textContent=display.name;$('#screen-select').append(o);}if(info.tv)document.body.classList.add('tv-mode');}catch(e){fail(e);}}
import('./immersive.mjs').catch(fail);
if(!native&&'serviceWorker'in navigator&&/^https?:$/.test(location.protocol))navigator.serviceWorker.register('./sw.js').catch(()=>{});
