import {input,getSession} from './app.mjs';
const $=s=>document.querySelector(s),viewport=$('#viewport'),keyboard=$('#native-keyboard');let editable=false,lastTap=0,composing=false,pointer={x:.5,y:.5},trackpad=false,lastMove=0;const touches=new Map();
let zoom=1,panX=0,panY=0,pinch=null;
$('#session').append(keyboard);
window.addEventListener('linkdesk-editable',e=>{editable=e.detail;if(!editable&&document.activeElement===keyboard)keyboard.blur();});
window.addEventListener('linkdesk-connected',e=>{$('#tv-layout').hidden=!e.detail.tv;$('#watch-only').checked=e.detail.control===false;$('#watch-only').disabled=e.detail.control===false;$('#session').dataset.layout='mix';resetZoom();});
function enabled(){return getSession()?.approved&&!$('#watch-only').checked;}
// Локальный масштаб: показывает увеличенную область у смотрящего, не влияя на управляемое устройство.
function base(){const video=$('#remote-video'),img=$('#remote-screen'),r=viewport.getBoundingClientRect(),w=video.hidden?img.naturalWidth:video.videoWidth,h=video.hidden?img.naturalHeight:video.videoHeight;if(!w||!h)return null;const scale=Math.min(r.width/w,r.height/h),bw=w*scale,bh=h*scale;return{r,B:{left:r.left+(r.width-bw)/2,top:r.top+(r.height-bh)/2,width:bw,height:bh}};}
function bounds(){const b=base();if(!b)return null;const {r,B}=b;if(zoom===1&&!panX&&!panY)return B;const cx=r.left+r.width/2,cy=r.top+r.height/2;return{left:cx+zoom*(B.left-cx)+panX,top:cy+zoom*(B.top-cy)+panY,width:B.width*zoom,height:B.height*zoom};}
function applyTransform(){const t=zoom===1?'':`translate(${panX}px,${panY}px) scale(${zoom})`;$('#remote-video').style.transform=t;$('#remote-screen').style.transform=t;}
function resetZoom(){zoom=1;panX=0;panY=0;pinch=null;applyTransform();}
function clampPan(){if(zoom<=1.02){resetZoom();return;}const b=base();if(!b)return;const {r,B}=b;const cx=r.left+r.width/2,cy=r.top+r.height/2,dispW=B.width*zoom,dispH=B.height*zoom,left0=cx+zoom*(B.left-cx),top0=cy+zoom*(B.top-cy);if(dispW<=r.width)panX=0;else panX=Math.min(r.left-left0,Math.max(r.right-left0-dispW,panX));if(dispH<=r.height)panY=0;else panY=Math.min(r.top-top0,Math.max(r.bottom-top0-dispH,panY));}
function pinchMove(){const a=[...touches.values()];if(a.length<2)return;const [p,q]=a,dist=Math.hypot(p.x-q.x,p.y-q.y),mid={x:(p.x+q.x)/2,y:(p.y+q.y)/2};if(!pinch){pinch={dist,mid};return;}if(pinch.dist>0)zoom=Math.max(1,Math.min(5,zoom*dist/pinch.dist));panX+=mid.x-pinch.mid.x;panY+=mid.y-pinch.mid.y;pinch={dist,mid};clampPan();applyTransform();}
function point(e){const r=bounds();if(!r)return null;return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
function openKeyboard(){if(!enabled())return;keyboard.value='';keyboard.focus({preventScroll:true});}
viewport.addEventListener('pointerdown',e=>{if(!enabled())return;const p=point(e);if(!p)return;e.preventDefault();viewport.focus();viewport.setPointerCapture(e.pointerId);touches.set(e.pointerId,{...p,startX:e.clientX,startY:e.clientY,x:e.clientX,y:e.clientY,time:Date.now(),moved:false,multi:touches.size>0});if(touches.size>1)for(const t of touches.values())t.multi=true;if(e.pointerType==='mouse'){pointer=p;input({type:'pointer',...p,action:'down',button:e.button===2?'right':'left'});}});
viewport.addEventListener('pointermove',e=>{if(!enabled())return;const p=point(e);if(!p)return;const t=touches.get(e.pointerId);const now=Date.now();if(now-lastMove<30)return;lastMove=now;if(e.pointerType==='mouse'){pointer=p;input({type:'pointer',...p,action:'move'});return;}if(!t)return;const dx=e.clientX-t.x,dy=e.clientY-t.y;t.x=e.clientX;t.y=e.clientY;if(Math.hypot(e.clientX-t.startX,e.clientY-t.startY)>7)t.moved=true;if(t.multi){pinchMove();return;}if(trackpad){const r=bounds();pointer.x=Math.max(0,Math.min(1,pointer.x+dx/r.width));pointer.y=Math.max(0,Math.min(1,pointer.y+dy/r.height));input({type:'pointer',...pointer,action:'move'});const c=$('#touch-cursor');c.hidden=false;c.style.left=pointer.x*100+'%';c.style.top=pointer.y*100+'%';}});
viewport.addEventListener('pointerup',e=>{const t=touches.get(e.pointerId);touches.delete(e.pointerId);if(touches.size<2)pinch=null;if(!t||!enabled())return;const p=point(e)||pointer,duration=Date.now()-t.time;if(e.pointerType==='mouse'){input({type:'pointer',...p,action:'up',button:e.button===2?'right':'left'});return;}if(t.multi)return;if(trackpad){if(!t.moved)input({type:'pointer',...pointer,action:duration>600?'long':'click',button:'left'});}else{pointer=p;const start=point({clientX:t.startX,clientY:t.startY})||p;input(t.moved?{type:'gesture',x:start.x,y:start.y,toX:p.x,toY:p.y,duration}:{type:'pointer',...p,action:duration>600?'long':'click',button:'left'});}if(!t.moved&&duration<500){if(editable||Date.now()-lastTap<380)openKeyboard();lastTap=Date.now();}});
viewport.addEventListener('pointercancel',e=>{touches.delete(e.pointerId);if(touches.size<2)pinch=null;input({type:'pointer',...pointer,action:'up',button:'left'});});viewport.addEventListener('contextmenu',e=>e.preventDefault());viewport.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();zoom=Math.max(1,Math.min(5,zoom*(e.deltaY<0?1.12:0.9)));clampPan();applyTransform();return;}if(!enabled())return;e.preventDefault();input({type:'scroll',x:e.deltaX,y:e.deltaY});},{passive:false});
keyboard.addEventListener('compositionstart',()=>composing=true);keyboard.addEventListener('compositionend',e=>{composing=false;if(e.data)input({type:'text',text:e.data});keyboard.value='';});
keyboard.addEventListener('beforeinput',e=>{if(!enabled()||composing||e.isComposing)return;if(e.inputType.startsWith('delete')){e.preventDefault();input({type:'key',key:'backspace'});}else if(e.inputType==='insertLineBreak'||e.inputType==='insertParagraph'){e.preventDefault();input({type:'key',key:'enter'});}else if(e.data){e.preventDefault();input({type:'text',text:e.data});keyboard.value='';}});
$('#session-options').addEventListener('click',()=>$('#options-dialog').showModal());$('#close-options').addEventListener('click',()=>$('#options-dialog').close());$('#open-keyboard').addEventListener('click',()=>{$('#options-dialog').close();openKeyboard();});$('#reset-zoom')?.addEventListener('click',()=>{resetZoom();$('#options-dialog').close();});$('#gesture-mode').addEventListener('change',e=>{trackpad=e.target.value==='trackpad';$('#touch-cursor').hidden=!trackpad;});$('#tv-layout').addEventListener('change',e=>$('#session').dataset.layout=e.target.value);
const resize=()=>{if(window.visualViewport&&$('#session').open)$('#session').style.height=window.visualViewport.height+'px';};window.visualViewport?.addEventListener('resize',resize);window.addEventListener('linkdesk-connected',resize);
