const {app,BrowserWindow,ipcMain,desktopCapturer,screen,dialog,shell,systemPreferences,globalShortcut}=require('electron');
const path=require('node:path'),os=require('node:os');
let win,approved=false,allowControl=false,selected,heartbeat=0,robot=null,mouseDown=false;
try{robot=require('@jitsi/robotjs');robot.setMouseDelay(0);robot.setKeyboardDelay(0);}catch(e){console.error('Input backend unavailable:',e.message);}
function release(){if(robot&&mouseDown){try{robot.mouseToggle('up','left');robot.mouseToggle('up','right');}catch{}}mouseDown=false;}
function stop(){approved=false;allowControl=false;release();if(win&&!win.isDestroyed()){win.setTitle('LinkDesk');win.webContents.send('stopped');}}
const origin=()=>new URL('file://'+path.join(__dirname,'../web/client.html').replace(/\\/g,'/')).href;
function local(event){if(event.sender!==win?.webContents||!event.senderFrame||event.senderFrame!==win.webContents.mainFrame)throw Error('Forbidden');}
function handle(name,fn){ipcMain.handle('linkdesk:'+name,async(e,...args)=>{local(e);return fn(...args);});}
function gate(){if(!approved||Date.now()-heartbeat>20000)throw Error('Доступ не разрешён или связь потеряна');}
const num=(n,min=0,max=1)=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max;
function position(x,y){if(!num(x)||!num(y))throw Error('Invalid coordinates');const d=screen.getAllDisplays().find(d=>String(d.id)===selected);if(!d)throw Error('Экран отключён');const p={x:Math.round(d.bounds.x+x*(d.bounds.width-1)),y:Math.round(d.bounds.y+y*(d.bounds.height-1))};return process.platform==='win32'?screen.dipToScreenPoint(p):p;}
const allowedKeys=new Set('backspace delete enter tab escape up down left right home end pageup pagedown space f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 audio_mute audio_vol_down audio_vol_up audio_play'.split(' '));
async function input(v){gate();if(!allowControl)return;if(!robot)throw Error('Модуль управления недоступен');if(!v||typeof v!=='object')throw Error('Invalid event');
 if(v.type==='pointer'){const p=position(v.x,v.y),button=v.button==='right'?'right':'left';robot.moveMouse(p.x,p.y);if(v.action==='down'||v.action==='drag'){if(!mouseDown){robot.mouseToggle('down',button);mouseDown=true;}}else if(v.action==='up'){release();}else if(['click','long'].includes(v.action)){release();robot.mouseClick(v.action==='long'?'right':button);}}
 else if(v.type==='gesture'){const start=position(v.x,v.y),end=position(v.toX,v.toY);release();robot.moveMouse(start.x,start.y);robot.mouseToggle('down','left');mouseDown=true;try{for(let i=1;i<=12;i++){gate();robot.moveMouse(Math.round(start.x+(end.x-start.x)*i/12),Math.round(start.y+(end.y-start.y)*i/12));await new Promise(r=>setTimeout(r,25));}}finally{release();}}
 else if(v.type==='scroll'){if(!num(v.x,-10000,10000)||!num(v.y,-10000,10000))return;robot.scrollMouse(Math.round(v.x/40),-Math.round(v.y/40));}
 else if(v.type==='key'){if(typeof v.key!=='string'||!(allowedKeys.has(v.key)||/^[a-z0-9]$/.test(v.key)))return;const mods=Array.isArray(v.modifiers)?v.modifiers.filter(x=>['control','command','alt','shift'].includes(x)).slice(0,4):[];robot.keyTap(v.key,mods);}
 else if(v.type==='text'){if(typeof v.text!=='string'||v.text.length>2000)return;robot.typeString(v.text);}
}
app.whenReady().then(()=>{
 win=new BrowserWindow({width:1220,height:920,minWidth:480,minHeight:620,title:'LinkDesk',backgroundColor:'#f6f7f2',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true,backgroundThrottling:false}});
 win.webContents.setWindowOpenHandler(({url})=>{if(/^https:\/\/(github\.com|linkdesk-ios\.vercel\.app|linkdesk-remote\.vercel\.app)\//.test(url))shell.openExternal(url);return{action:'deny'};});
 win.webContents.on('will-navigate',(e,url)=>{e.preventDefault();if(/^https:\/\/(github\.com|linkdesk-ios\.vercel\.app|linkdesk-remote\.vercel\.app)\//.test(url))shell.openExternal(url);});
 win.webContents.session.setPermissionRequestHandler((wc,permission,callback)=>callback(wc===win.webContents&&approved&&permission==='media'));win.webContents.session.setDisplayMediaRequestHandler(async(request,callback)=>{if(!approved||request.frame!==win.webContents.mainFrame){callback({});return;}try{const sources=await desktopCapturer.getSources({types:['screen'],thumbnailSize:{width:0,height:0}});const source=sources.find(s=>s.display_id===selected);callback(approved&&source?{video:source}:{});}catch{callback({});}});
 win.webContents.on('render-process-gone',stop);win.on('closed',()=>{approved=false;release();win=null;});
 handle('info',()=>({platform:process.platform,model:os.hostname(),tv:false,screens:screen.getAllDisplays().map((d,i)=>({id:String(d.id),name:`Экран ${i+1} · ${d.size.width} × ${d.size.height}`}))}));
 handle('permissions',async()=>{if(!robot)return'Не удалось загрузить модуль управления. Переустановите приложение.';if(process.platform==='darwin'){systemPreferences.isTrustedAccessibilityClient(true);await shell.openExternal('x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture');return'Разрешите LinkDesk запись экрана и Универсальный доступ, затем перезапустите приложение.';}return'Для обычных приложений разрешения готовы. Windows UAC и приложения администратора могут быть недоступны.';});
 handle('approve',async(name,sas,display)=>{if(approved)return false;if(!screen.getAllDisplays().some(d=>String(d.id)===display))throw Error('Выберите экран');win.show();win.focus();const r=await dialog.showMessageBox(win,{type:'question',title:'Разрешить удалённое управление?',message:`${String(name).slice(0,80)} просит доступ`,detail:`Разрешить просмотр выбранного экрана, управление мышью и клавиатурой? Код проверки: ${String(sas).slice(0,6)}.\n\nДля немедленной остановки: Ctrl+Alt+Shift+Q (Mac: ⌘⌥⇧Q) или закройте LinkDesk.`,buttons:['Отклонить','Только наблюдение','Разрешить управление'],defaultId:0,cancelId:0,noLink:true});if(r.response===0)return false;allowControl=r.response===2;if(allowControl&&!robot)throw Error('Модуль управления не загрузился');if(allowControl&&process.platform==='darwin'&&!systemPreferences.isTrustedAccessibilityClient(true))throw Error('Включите LinkDesk в Универсальном доступе и повторите подключение.');selected=display;heartbeat=Date.now();approved=true;win.setTitle('● LinkDesk — УДАЛЁННОЕ УПРАВЛЕНИЕ ВКЛЮЧЕНО');return {control:allowControl};});
 handle('editable',()=>false);
 handle('heartbeat',()=>{gate();heartbeat=Date.now();return true;});handle('stop',()=>{stop();return true;});handle('input',input);
 handle('capture',async quality=>{gate();const width=quality==='fast'?960:quality==='sharp'?1920:1280;const d=screen.getAllDisplays().find(d=>String(d.id)===selected);if(!d)throw Error('Экран отключён');const sources=await desktopCapturer.getSources({types:['screen'],thumbnailSize:{width,height:Math.round(width*d.size.height/d.size.width)},fetchWindowIcons:false});gate();const source=sources.find(s=>s.display_id===selected);if(!source||source.thumbnail.isEmpty())throw Error('Нет разрешения на запись экрана');const jpg=source.thumbnail.toJPEG(quality==='sharp'?75:quality==='fast'?40:58);return{data:'data:image/jpeg;base64,'+jpg.toString('base64'),width:d.size.width,height:d.size.height};});
 globalShortcut.register('CommandOrControl+Alt+Shift+Q',stop);setInterval(()=>{if(approved&&Date.now()-heartbeat>20000)stop();},2000);
 win.loadFile(path.join(__dirname,'../web/client.html'));
});
app.on('window-all-closed',()=>app.quit());app.on('will-quit',()=>{release();globalShortcut.unregisterAll();});
